version: "3.8"

services:
  react:
    container_name: react-startup_react
    build:
      dockerfile: ./container/Dockerfile
      context: ./
      target: development
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - ./container/entrypoint.sh:/entrypoint.sh
      - node_modules:/app/node_modules # volume trick for node_modules

volumes:
  node_modules
